import request from './request'

export const createRootDomain = (data) => request.post('/admin/domains', data)
export const listDomains = () => request.get('/admin/domains')
export const assignDomain = (id, data) => request.post(`/admin/domains/${id}/assign`, data)
export const listUsers = () => request.get('/admin/users')
export const updateUser = (id, data) => request.put(`/admin/users/${id}`, data)
export const adminResetPassword = (id, data) => request.post(`/admin/users/${id}/reset-password`, data)
export const disableUser = (id) => request.delete(`/admin/users/${id}`)
export const listLogs = (params) => request.get('/admin/logs', { params })
export const retrySync = (id) => request.post(`/admin/records/${id}/sync`)
export const getSettings = (category) => request.get(`/admin/settings/${category}`)
export const updateSettings = (category, data) => request.put(`/admin/settings/${category}`, data)
export const testSMTP = (data, config) => request.post('/admin/settings/smtp/test', data, config)
export const promoteToAdmin = (id) => request.post(`/admin/users/${id}/promote`)
export const demoteFromAdmin = (id) => request.post(`/admin/users/${id}/demote`)

export const getAdminDomainTree = () => request.get('/admin/domains/tree')
export const getAdminDomainDetail = (id) => request.get(`/admin/domains/${id}/detail`)
export const adminChangeOwner = (id, userId) => request.post(`/admin/domains/${id}/change-owner`, { user_id: userId })
export const adminRevokePermission = (id, userId) => request.delete(`/admin/domains/${id}/permissions/${userId}`)
