import request from './request'

export const login = (data) => request.post('/auth/login', data)
export const register = (data) => request.post('/auth/register', data)
export const getProfile = () => request.get('/auth/profile')
export const updateProfile = (data) => request.put('/auth/profile', data)
export const resetToken = () => request.put('/auth/token')
export const changePassword = (data) => request.put('/auth/password', data)
export const forgotPassword = (data) => request.post('/auth/forgot-password', data)
export const resetPassword = (data) => request.post('/auth/reset-password', data)
export const checkUsername = (username) => request.get('/auth/check-username', { params: { username } })
export const uploadAvatar = (formData, config) => request.post('/auth/avatar', formData, { headers: { 'Content-Type': 'multipart/form-data' }, ...config })
export const getMyLogs = (params) => request.get('/auth/logs', { params })
export const grantInviteQuota = (data, config) => request.post('/auth/grant-invite', data, config)
export const revokeInviteQuota = (data, config) => request.post('/auth/revoke-invite', data, config)
export const getInviteLogs = (params) => request.get('/auth/invite-logs', { params })
export const getPendingReturns = () => request.get('/auth/pending-returns')
export const searchAllUsers = (q) => request.get('/auth/users/search', { params: { q } })
export const deleteAccount = (config) => request.delete('/auth/account', config)
export const sendVerifyEmail = (data, config) => request.post('/auth/send-verify-email', data, config)
export const verifyEmail = (data, config) => request.post('/auth/verify-email', data, config)
