package notification

const (
	CatPermissionGranted   = "permission_granted"
	CatPermissionRevoked   = "permission_revoked"
	CatPermissionRevokeReq = "permission_revoke_request"
	CatPermissionReturned  = "permission_returned"
	CatDomainTransferred   = "domain_transferred"
	CatDomainReclaimed     = "domain_reclaimed"
	CatDomainDeleted       = "domain_deleted"
	CatDomainArchived      = "domain_archived"
	CatDomainReactivated   = "domain_reactivated"
	CatRecordTrashed       = "record_trashed"
	CatRecordRestored      = "record_restored"
	CatSyncFailed          = "sync_failed"
	CatAdminPromoted       = "admin_promoted"
	CatAdminDemoted        = "admin_demoted"
	CatAdminPasswordReset  = "admin_password_reset"
	CatAdminDisabled       = "admin_disabled"
	CatAdminGrantInvite    = "admin_grant_invite"
	CatAdminRevokeInvite   = "admin_revoke_invite"
	CatUserWelcome         = "user_welcome"
	CatEmailVerified       = "email_verified"
	CatDDNSUpdateOK        = "ddns_update_ok"
	CatDDNSUpdateFailed    = "ddns_update_failed"
	CatFriendRequest       = "friend_request_received"
	CatFriendAccepted      = "friend_request_accepted"
	CatFriendRejected      = "friend_request_rejected"
	CatProviderClaimed     = "provider_claimed"
	CatProviderReclaimed   = "provider_reclaimed"
	CatProviderDeleted     = "provider_deleted"
	CatAdminBroadcast      = "admin_broadcast"
)
