package errs

// Validation errors (400)
const (
	InvalidRequest             Code = "INVALID_REQUEST"
	InvalidRequestBody         Code = "INVALID_REQUEST_BODY"
	InvalidJSON                Code = "INVALID_JSON"
	InvalidEmail               Code = "INVALID_EMAIL"
	InvalidNodeID              Code = "INVALID_NODE_ID"
	InvalidRecordID            Code = "INVALID_RECORD_ID"
	InvalidUserID              Code = "INVALID_USER_ID"
	InvalidNotificationID      Code = "INVALID_NOTIFICATION_ID"
	InvalidID                  Code = "INVALID_ID"
	InvalidTokenID             Code = "INVALID_TOKEN_ID"
	InvalidRequestID           Code = "INVALID_REQUEST_ID"
	InvalidFriendID            Code = "INVALID_FRIEND_ID"
	InvalidParentNodeID        Code = "INVALID_PARENT_NODE_ID"
	InvalidProviderID          Code = "INVALID_PROVIDER_ID"
	InvalidProviderIDAdmin      Code = "INVALID_PROVIDER_ID_ADMIN"
	InvalidPresetID            Code = "INVALID_PRESET_ID"
	InvalidOperation           Code = "INVALID_OPERATION"
	InvalidParams              Code = "INVALID_PARAMS"
	MessageContentRequired     Code = "MESSAGE_CONTENT_REQUIRED"
	TokenNameRequired          Code = "TOKEN_NAME_REQUIRED"
	PresetNameRequired         Code = "PRESET_NAME_REQUIRED"
	UsernameRequired           Code = "USERNAME_REQUIRED"
	AmountMustBePositive       Code = "AMOUNT_MUST_BE_POSITIVE"
	UploadCSVRequired          Code = "UPLOAD_CSV_REQUIRED"
	CSVNeedsHeaderAndData      Code = "CSV_NEEDS_HEADER_AND_DATA"
	ReadRequestBodyFailed      Code = "READ_REQUEST_BODY_FAILED"
	NoRecordsToImport          Code = "NO_RECORDS_TO_IMPORT"
	NoFieldsToUpdate           Code = "NO_FIELDS_TO_UPDATE"
	ImageFormatNotAllowed      Code = "IMAGE_FORMAT_NOT_ALLOWED"
	InvalidIPv4Value           Code = "INVALID_IPV4_VALUE"
	InvalidIPv6Value           Code = "INVALID_IPV6_VALUE"
	MXPriorityRequired         Code = "MX_PRIORITY_REQUIRED"
	MXValueMustBeDomain        Code = "MX_VALUE_MUST_BE_DOMAIN"
	SRVFormatInvalid           Code = "SRV_FORMAT_INVALID"
	SRVPriorityMustBeNumber    Code = "SRV_PRIORITY_MUST_BE_NUMBER"
	SRVWeightMustBeNumber      Code = "SRV_WEIGHT_MUST_BE_NUMBER"
	SRVPortMustBeNumber        Code = "SRV_PORT_MUST_BE_NUMBER"
	SRVPortRangeInvalid        Code = "SRV_PORT_RANGE_INVALID"
	SRVTargetMustBeDomain      Code = "SRV_TARGET_MUST_BE_DOMAIN"
	CAAFormatInvalid           Code = "CAA_FORMAT_INVALID"
	CAAFlagRangeInvalid        Code = "CAA_FLAG_RANGE_INVALID"
	SearchKeywordTooShort      Code = "SEARCH_KEYWORD_TOO_SHORT"
	RAMTokenInvalid            Code = "RAM_TOKEN_INVALID"
	AccessKeyIDInvalid         Code = "ACCESS_KEY_ID_INVALID"
	InviteCodeInvalid          Code = "INVITE_CODE_INVALID"
	TransferTargetRequired     Code = "TRANSFER_TARGET_REQUIRED"
	RootRecordNotTransferable  Code = "ROOT_RECORD_NOT_TRANSFERABLE"
	NoParentChildRelation      Code = "NO_PARENT_CHILD_RELATION"
	GroupNameRequired          Code = "GROUP_NAME_REQUIRED"
	GroupNameUnchanged         Code = "GROUP_NAME_UNCHANGED"
	InviteLimitNegative       Code = "INVITE_LIMIT_NEGATIVE"
	VerifyCodeInvalidOrExpired  Code = "VERIFY_CODE_INVALID_OR_EXPIRED"
	VerifyCodeSentIfEmailExists Code = "VERIFY_CODE_SENT_IF_EMAIL_EXISTS"
	VerifyCodeSent             Code = "VERIFY_CODE_SENT"
	SMTPNotConfigured          Code = "SMTP_NOT_CONFIGURED"
)

// Not Found errors (404)
const (
	NodeNotFound             Code = "NODE_NOT_FOUND"
	DomainNodeNotFound       Code = "DOMAIN_NODE_NOT_FOUND"
	RecordNotFound           Code = "RECORD_NOT_FOUND"
	DomainNotFound           Code = "DOMAIN_NOT_FOUND"
	UserNotFound             Code = "USER_NOT_FOUND"
	TargetUserNotFound       Code = "TARGET_USER_NOT_FOUND"
	DNSProviderNotFound      Code = "DNS_PROVIDER_NOT_FOUND"
	ProviderNotFound         Code = "PROVIDER_NOT_FOUND"
	NotificationNotFound     Code = "NOTIFICATION_NOT_FOUND"
	RequestNotFound          Code = "REQUEST_NOT_FOUND"
	FriendRelationNotFound   Code = "FRIEND_RELATION_NOT_FOUND"
	PermissionNotFound       Code = "PERMISSION_NOT_FOUND"
	PermissionRecordNotFound  Code = "PERMISSION_RECORD_NOT_FOUND"
	InviteCodeNotFound       Code = "INVITE_CODE_NOT_FOUND"
	TokenNotFound            Code = "TOKEN_NOT_FOUND"
	PresetNotFound           Code = "PRESET_NOT_FOUND"
	ParentNodeNotFound       Code = "PARENT_NODE_NOT_FOUND"
	ReceiverNotFound         Code = "RECEIVER_NOT_FOUND"
	InviterNotFound          Code = "INVITER_NOT_FOUND"
	InviteeNotFound          Code = "INVITEE_NOT_FOUND"
	DomainNotFoundOrNoAccess  Code = "DOMAIN_NOT_FOUND_OR_NO_ACCESS"
	RecordNotInTrash         Code = "RECORD_NOT_IN_TRASH"
)

// Auth errors (401)
const (
	InvalidCredentials Code = "INVALID_CREDENTIALS"
	AccountDisabled    Code = "ACCOUNT_DISABLED"
	LoginRequired      Code = "LOGIN_REQUIRED"
)

// Permission errors (403)
const (
	NoPermission                    Code = "NO_PERMISSION"
	NoAccess                        Code = "NO_ACCESS"
	NoPermissionForRecord           Code = "NO_PERMISSION_FOR_RECORD"
	NoPermissionForProvider         Code = "NO_PERMISSION_FOR_PROVIDER"
	CannotGrantHigherPermission     Code = "CANNOT_GRANT_HIGHER_PERMISSION"
	OnlyHolderOrAdminAccept         Code = "ONLY_HOLDER_OR_ADMIN_ACCEPT"
	OnlyHolderReject                Code = "ONLY_HOLDER_REJECT"
	CannotEditSuperAdmin            Code = "CANNOT_EDIT_SUPER_ADMIN"
	CannotEditOtherAdmin            Code = "CANNOT_EDIT_OTHER_ADMIN"
	OnlySuperAdminChangeRole        Code = "ONLY_SUPER_ADMIN_CHANGE_ROLE"
	CannotResetSuperAdminPassword    Code = "CANNOT_RESET_SUPER_ADMIN_PASSWORD"
	CannotDisableSelf               Code = "CANNOT_DISABLE_SELF"
	OnlySuperAdminDisableSuperAdmin  Code = "ONLY_SUPER_ADMIN_DISABLE_SUPER_ADMIN"
	CannotDisableOtherAdmin          Code = "CANNOT_DISABLE_OTHER_ADMIN"
	OnlySuperAdminPromote           Code = "ONLY_SUPER_ADMIN_PROMOTE"
	OnlySuperAdminDemote             Code = "ONLY_SUPER_ADMIN_DEMOTE"
	CannotDemoteSuperAdmin           Code = "CANNOT_DEMOTE_SUPER_ADMIN"
	SuperAdminCannotDelete           Code = "SUPER_ADMIN_CANNOT_DELETE"
	CannotRevokeOwnerPermission     Code = "CANNOT_REVOKE_OWNER_PERMISSION"
	NotRequestReceiver              Code = "NOT_REQUEST_RECEIVER"
	NotSubdomainOwner               Code = "NOT_SUBDOMAIN_OWNER"
	NotSubdomainOwner2              Code = "NOT_SUBDOMAIN_OWNER_2"
)

// Conflict errors (409)
const (
	UsernameExists                   Code = "USERNAME_EXISTS"
	UsernameTaken                    Code = "USERNAME_TAKEN"
	DomainAlreadyExists              Code = "DOMAIN_ALREADY_EXISTS"
	DomainAlreadyInSystem            Code = "DOMAIN_ALREADY_IN_SYSTEM"
	RecordAlreadyExists              Code = "RECORD_ALREADY_EXISTS"
	SubdomainInUse                   Code = "SUBDOMAIN_IN_USE"
	AlreadyFriends                   Code = "ALREADY_FRIENDS"
	FriendRequestPending             Code = "FRIEND_REQUEST_PENDING"
	RequestAlreadyProcessed          Code = "REQUEST_ALREADY_PROCESSED"
	CannotMessageSelf                Code = "CANNOT_MESSAGE_SELF"
	CannotAddSelfAsFriend            Code = "CANNOT_ADD_SELF_AS_FRIEND"
	CannotAssignInviteToSelf         Code = "CANNOT_ASSIGN_INVITE_TO_SELF"
	CannotRevokeSelfInvite           Code = "CANNOT_REVOKE_SELF_INVITE"
	NoRevocableInviteQuota           Code = "NO_REVOCABLE_INVITE_QUOTA"
	NoRevocableInviteQuotaGlobal     Code = "NO_REVOCABLE_INVITE_QUOTA_GLOBAL"
	CannotDeleteUsedInviteCode        Code = "CANNOT_DELETE_USED_INVITE_CODE"
	UserAlreadyAdmin                 Code = "USER_ALREADY_ADMIN"
	UserNotAdmin                     Code = "USER_NOT_ADMIN"
	CannotReclaimOwnNode             Code = "CANNOT_RECLAIM_OWN_NODE"
	NotificationActionNotSupported    Code = "NOTIFICATION_ACTION_NOT_SUPPORTED"
	NotificationAlreadyProcessed      Code = "NOTIFICATION_ALREADY_PROCESSED"
	DomainArchived                   Code = "DOMAIN_ARCHIVED"
	DomainNotArchived                Code = "DOMAIN_NOT_ARCHIVED"
	NodeNotArchived                  Code = "NODE_NOT_ARCHIVED"
	NodeNoProviderBound              Code = "NODE_NO_PROVIDER_BOUND"
	NodeNotFromRecord                Code = "NODE_NOT_FROM_RECORD"
	RootNodeCannotDowngrade          Code = "ROOT_NODE_CANNOT_DOWNGRADE"
	CannotDowngradeWithChildren      Code = "CANNOT_DOWNGRADE_WITH_CHILDREN"
	CannotDowngradeWithPermissions   Code = "CANNOT_DOWNGRADE_WITH_PERMISSIONS"
	CannotDowngradeWithProvider      Code = "CANNOT_DOWNGRADE_WITH_PROVIDER"
	ArchiveRootBeforeDelete          Code = "ARCHIVE_ROOT_BEFORE_DELETE"
	CannotDeleteWithChildren         Code = "CANNOT_DELETE_WITH_CHILDREN"
	NoRecordsForConversion           Code = "NO_RECORDS_FOR_CONVERSION"
	CannotReturnRootDomain           Code = "CANNOT_RETURN_ROOT_DOMAIN"
	DomainDeletedCannotSync          Code = "DOMAIN_DELETED_CANNOT_SYNC"
	DomainArchivedCannotSync         Code = "DOMAIN_ARCHIVED_CANNOT_SYNC"
	DomainNoProviderBound            Code = "DOMAIN_NO_PROVIDER_BOUND"
	ProviderDeletedCannotRestore      Code = "PROVIDER_DELETED_CANNOT_RESTORE"
	GroupNameExists                  Code = "GROUP_NAME_EXISTS"
	InvalidDomainOperation           Code = "INVALID_DOMAIN_OPERATION"
)

// Business logic errors (400)
const (
	NoDNSProviderAvailable   Code = "NO_DNS_PROVIDER_AVAILABLE"
	NoAvailableRootDomain    Code = "NO_AVAILABLE_ROOT_DOMAIN"
	TargetNodeArchived       Code = "TARGET_NODE_ARCHIVED"
	TargetNodeNotFound       Code = "TARGET_NODE_NOT_FOUND"
	SourceNodeNotFound       Code = "SOURCE_NODE_NOT_FOUND"
	AddedToSyncRetryQueue    Code = "ADDED_TO_SYNC_RETRY_QUEUE"
	TestEmailSent            Code = "TEST_EMAIL_SENT"
)

// Internal errors (500)
const (
	GenerateTokenFailed        Code = "GENERATE_TOKEN_FAILED"
	ResetTokenFailed           Code = "RESET_TOKEN_FAILED"
	GenerateVerifyCodeFailed   Code = "GENERATE_VERIFY_CODE_FAILED"
	CreateResetCodeFailed      Code = "CREATE_RESET_CODE_FAILED"
	ResetPasswordFailed        Code = "RESET_PASSWORD_FAILED"
	FileUploadFailed          Code = "FILE_UPLOAD_FAILED"
	ImageEncodeFailed          Code = "IMAGE_ENCODE_FAILED"
	AvatarSaveFailed           Code = "AVATAR_SAVE_FAILED"
	UpdateEmailFailed          Code = "UPDATE_EMAIL_FAILED"
	TakeoverFailed             Code = "TAKEOVER_FAILED"
	GetTransferDomainsFailed   Code = "GET_TRANSFER_DOMAINS_FAILED"
	PasswordEncryptFailed      Code = "PASSWORD_ENCRYPT_FAILED"
	InternalError              Code = "INTERNAL_ERROR"
)